version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=floorplan_db;Username=postgres;Password=postgres123
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - floorplan-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=floorplan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - floorplan-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - floorplan-network

volumes:
  postgres_data:

networks:
  floorplan-network:
    driver: bridge