@echo off
echo Starting all services with Docker...

echo Starting PostgreSQL...
docker run -d --name postgres-dev -e POSTGRES_PASSWORD=dev_password -e POSTGRES_DB=floorplan_dev -p 5432:5432 postgres:15

echo Starting Redis...
docker run -d --name redis-dev -p 6379:6379 redis:alpine

echo Starting Azurite (Azure Storage Emulator)...
docker run -d --name azurite-dev -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite

echo Waiting for services to start...
timeout /t 10

echo Setting up database...
cd src\Api
dotnet ef database update

echo Starting API...
dotnet run --urls "http://localhost:5000"